### ISSUE TITLE
Looting enchantment

### ISSUE THREAD

**Issue by Sybsuper** [Y3Z0N/theabyss#20]
### Describe the Suggestion

Add more loot drops when using looting to kill entities.
Places where drops are defined for easy modification:
Normal entities:
- https://github.com/Y3Z0N/theabyss/blob/main/src/main/java/net/yezon/theabyss/entity/DeerEntity.java#L132
- https://github.com/Y3Z0N/theabyss/blob/main/src/main/java/net/yezon/theabyss/entity/EndSpiderEntity.java#L141
- https://github.com/Y3Z0N/theabyss/blob/main/src/main/java/net/yezon/theabyss/entity/GuardEntity.java#L155
- https://github.com/Y3Z0N/theabyss/blob/main/src/main/java/net/yezon/theabyss/entity/IceKnightEntity.java#L137
- https://github.com/Y3Z0N/theabyss/blob/main/src/main/java/net/yezon/theabyss/entity/InfcetedCowEntity.java#L141
- https://github.com/Y3Z0N/theabyss/blob/main/src/main/java/net/yezon/theabyss/entity/InfectedCreeperEntity.java#L137
- https://github.com/Y3Z0N/theabyss/blob/main/src/main/java/net/yezon/theabyss/entity/InfectedPhantomEntity.java#L168
- https://github.com/Y3Z0N/theabyss/blob/main/src/main/java/net/yezon/theabyss/entity/InfectedSpiderEntity.java#L140
- https://github.com/Y3Z0N/theabyss/blob/main/src/main/java/net/yezon/theabyss/entity/InfectedZombieEntity.java#L144
- https://github.com/Y3Z0N/theabyss/blob/main/src/main/java/net/yezon/theabyss/entity/LaroFishEntity.java#L138
- https://github.com/Y3Z0N/theabyss/blob/main/src/main/java/net/yezon/theabyss/entity/LaroFishFlyEntity.java#L136
- https://github.com/Y3Z0N/theabyss/blob/main/src/main/java/net/yezon/theabyss/entity/LuroFishEntity.java#L138
- https://github.com/Y3Z0N/theabyss/blob/main/src/main/java/net/yezon/theabyss/entity/MagicalDeerEntity.java#L132
- https://github.com/Y3Z0N/theabyss/blob/main/src/main/java/net/yezon/theabyss/entity/MudZombieEntity.java#L139
- https://github.com/Y3Z0N/theabyss/blob/main/src/main/java/net/yezon/theabyss/entity/RaluFishEntity.java#L144
- https://github.com/Y3Z0N/theabyss/blob/main/src/main/java/net/yezon/theabyss/entity/ScorpionEntity.java#L141
- https://github.com/Y3Z0N/theabyss/blob/main/src/main/java/net/yezon/theabyss/entity/ShatteredZombieEntity.java#L144
- https://github.com/Y3Z0N/theabyss/blob/main/src/main/java/net/yezon/theabyss/entity/SlimeSpiderEntity.java#L138
- https://github.com/Y3Z0N/theabyss/blob/main/src/main/java/net/yezon/theabyss/entity/SoulGuardEntity.java#L155

Bosses (probably no need to change these):
- https://github.com/Y3Z0N/theabyss/blob/main/src/main/java/net/yezon/theabyss/entity/CrystalGolemEntity.java#L150
- https://github.com/Y3Z0N/theabyss/blob/main/src/main/java/net/yezon/theabyss/entity/ElderEntity.java#L150
- https://github.com/Y3Z0N/theabyss/blob/main/src/main/java/net/yezon/theabyss/entity/NightbladeBossEntity.java#L145
- https://github.com/Y3Z0N/theabyss/blob/main/src/main/java/net/yezon/theabyss/entity/TheRokaEntity.java#L146

**Comment by Y3Z0N** [comment]
will be implemented in next pull

**Comment by LDsanya** [comment]
If you need, i can share already created loot tables.There is have a 30% chance of extra loot for each level of the loot enchantment, drop additional loot from such creatures:
deer 1-2 bonus deer_beef
end_spider 1 bonus nether_nugget
guard 2-4 bonus gold_nugget
ice_knight 1-2 bonus knight_shard
infceted_cow 1-2 bonus rotten_flesh
infected_creeper 1-2 bonus creeper_dust
infected_phantom 1 bonus phantom_soul_item
infected_spider 2-4 bonus string
infected_zombie 1-2 bonus rotten_flesh
magical_deer 1-2 bonus deer_beef
mud_zombie 1-2 bonus rotten_flesh
scorpion 1 bonus scorpion_eye
shattered_zombie 1-2 bonus rotten_flesh
slime_spider 1-2 bonus slime_stage_1
soul_guard 1 bonus soul_heart

I didn't change the rest because I don't think it's necessary
[data.zip](https://github.com/Y3Z0N/theabyss/files/7982167/data.zip)

**Comment by Y3Z0N** [comment]
Thank you @LDsanya i‘ll implement it 😊

**Comment by Y3Z0N** [comment]
added to 2.2.3-1
