### ISSUE TITLE
Error rendering IceSkeletonEntity$GlowingLayer

### ISSUE THREAD

**Issue by marcell123455** [Y3Z0N/theabyss#36]
### Describe the Bug

When the mod is running on a server, a player joins the ice dimension and a IceSkeleton is loaded, it crashes the server.
Everything works fine in singleplayer.

### Reproduction Steps

1.Create a forge server and put the abyss in mods
2join the ice dimension

...

### Expected Result

3.when a ice skeleton is loaded it crashes the server

### Crash Report or Log

https://pastebin.com/gP4zpWVq

### Operating System

Windows 11

### Mod Version

2.2.2

### Minecraft Version

1.16.5

### Forge Version

1.16.5-36.2.23

### Other Mods

Watch the crash report

**Comment by Y3Z0N** [comment]
could not reproduce this error with the glowing layer. It seems like a incompatibility between a other mod which changes or override mob textures.

**Comment by Y3Z0N** [comment]
can you try it again without infernal mobs? and tell me if this happens again.

**Comment by marcell123455** [comment]
Ok, I can confirm this crash is fixed when removing infernal mobs. I just wonder why infernal mobs tries to change a texture, what the mod actually never does and why it´s only happening when it´s on a server.

Anyhow, sorry for the inconvenience. ;)

**Comment by Y3Z0N** [comment]
i don’t think that it changes the texture at all but it seems like to mess with mob class. report the issue to the developer

**Comment by AtomicStryker** [comment]
Hi! So, looking at your source "private static class GlowingLayer" in IceSkeletonEntity looks really questionable to me. Its very much clientside code in a server class. You have it annotated with "@OnlyIn(Dist.CLIENT)" but apparently calling IceSkeletonEntity.class.getSimpleClassName will still crash on a server (what Infernal Mobs does), so that isn't safe enough.

Looking at your code, i dont see any reason why ModelRegisterHandler and GlowingLayer are in that (server-used) class. Can i suggest moving them into a seperate Renderer class?
