### ISSUE TITLE
Cannot find abandoned house

### ISSUE THREAD

**Issue by estaskris** [Y3Z0N/theabyss#54]
For the forest biome, can it be any forest biome? I. E. Dark forest, charred forest, birch forest etc. And is there an easier way to locate the abandoned house?

**Comment by Y3Z0N** [comment]
use /locate

**Comment by Y3Z0N** [comment]
will be fixed in 1.19.2 (1.18.2 is not supported anymore)

**Comment by Amadalia2** [comment]
So are you saying we can no longer use Abyss II on 1.18.2? Because we did the locate command and couldn't find, so we dropped a broken radio and used it and created a portal and went in, got some items, created the infuser, but the bottle of somnium will not go into the spot it is supposed to to create the anti-infection essence. We also can't find the recipe for the anti-fear, though i assume it's similar with a different item?

**Comment by Y3Z0N** [comment]
1.16.5, 1.18.2 are not supported anymore closed
