### ISSUE TITLE
Server crashes when a new player joins related to the abyss book generating in inventory 

### ISSUE THREAD

**Issue by Neptainium** [Y3Z0N/theabyss#7]
the crash log is attached below. When a new player joins (fresh player data) the server crashes due to a ticking error. this error is cited to be caused by the event which handles giving the player the abyss book when they first join. it's fine after the server crashes but we can't have the server crash every time a new player joins.  I've also attached a full mod list separated by mods, libraries, and client-side mods as well as all plugins loaded on the server and a link to the server jar we use. this was not a problem with the pre 2.0.0 versions of the abyss and has only started since we updated. 

https://docs.google.com/spreadsheets/d/1khi8qzY3s4lxnNea_-M1FBy-YQYR_DFXrnQMYb6Bj0k/edit?usp=sharing

https://github.com/IzzelAliz/Arclight

[crash-2022-01-06_23.11.44-server.txt](https://github.com/Y3Z0N/theabyss/files/7835595/crash-2022-01-06_23.11.44-server.txt)

**Comment by Y3Z0N** [comment]
You are using a unsupported and modified version of forge. in the logs you can clearly see that your issue is caused by some commands. theres not a single line about the abyss or any other mods. Seems like „Arclight“ can’t handle commands from other mods well. 


you should report that to the developer of Arclight:


`java.lang.AbstractMethodError: Receiver class net.minecraft.command.ICommandSource$1 does not define or inherit an implementation of the resolved method 'abstract org.bukkit.command.CommandSender bridge$getBukkitSender(net.minecraft.command.CommandSource)' of interface io.izzel.arclight.common.bridge.command.ICommandSourceBridge. `
